import Link from "next/link";
import { notFound } from "next/navigation";
import { connection } from "next/server";
import { deleteSupplier } from "@/actions/master-data";
import { DetailItem, EmptyState, PageHeader, StatusBadge, tableClass, tdClass, thClass } from "@/components/master-data-ui";
import { prisma } from "@/lib/prisma";
export default async function SupplierDetailPage({ params }: PageProps<"/suppliers/[id]">) { await connection(); const { id } = await params; const item = await prisma.supplier.findUnique({ where: { id }, include: { contracts: { orderBy: { effectiveDate: "desc" } } } }); if (!item) notFound(); return <div className="mx-auto max-w-7xl"><PageHeader description={item.supplierCode} title={item.supplierName}/><div className="mt-5 flex gap-3"><Link className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white" href={`/suppliers/${id}/edit`}>编辑供应商</Link><Link className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold" href={`/supplier-contracts/new?supplierId=${id}`}>新增供应商合同</Link><form action={deleteSupplier.bind(null, id)}><button className="rounded-xl border border-red-200 bg-white px-4 py-2 text-sm font-semibold text-red-700">删除供应商</button></form></div>
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4"><DetailItem label="状态" value={<StatusBadge status={item.status}/>}/><DetailItem label="服务区域" value={item.serviceArea}/><DetailItem label="联系人" value={item.contactName}/><DetailItem label="联系电话" value={item.contactPhone}/><DetailItem label="纳税人识别号" value={item.taxpayerIdentificationNo}/><DetailItem label="注册地址" value={item.registeredAddress}/><DetailItem label="开户银行" value={item.bankName}/><DetailItem label="银行账户名称" value={item.bankAccountName}/><DetailItem label="银行账号" value={item.bankAccountNo}/><DetailItem label="备注" value={item.remark}/></div></section>
  <section className="mt-8"><h2 className="text-xl font-bold">供应商框架合同</h2>{!item.contracts.length ? <div className="mt-4"><EmptyState>暂无供应商合同。</EmptyState></div> : <div className="overflow-x-auto"><table className={tableClass}><thead><tr><th className={thClass}>合同</th><th className={thClass}>有效期</th><th className={thClass}>状态</th><th className={thClass}>附件</th><th className={thClass}></th></tr></thead><tbody>{item.contracts.map((c) => <tr key={c.id}><td className={tdClass}><b>{c.contractName}</b><br/><span className="text-xs text-slate-400">{c.contractNo}</span></td><td className={tdClass}>{c.effectiveDate.toLocaleDateString("zh-CN")} – {c.expiryDate?.toLocaleDateString("zh-CN") ?? "长期"}</td><td className={tdClass}><StatusBadge status={c.status}/></td><td className={tdClass}>{c.attachmentUrl ? <a className="text-blue-700" href={c.attachmentUrl} target="_blank">打开</a> : "—"}</td><td className={tdClass}><Link className="font-semibold text-blue-700" href={`/supplier-contracts/${c.id}/edit`}>管理</Link></td></tr>)}</tbody></table></div>}</section></div>; }
